#ifndef AccuConference2_Constants_h
#define AccuConference2_Constants_h

#pragma mark List Conference

#define CONFERENCE_LINE_CELL_ID @"CONFERENCE_LINE_CELL_ID"

#define LIST_DETAIL_MODE 1
#define LIST_SELECT_SINGLE_MODE 2
#define LIST_SELECT_MULTIPLE_MODE 3

#pragma mark - Events

#define CONFERENCE_LINES_MODIFIED @"CONFERENCELINES_MODIFIED"

#define CREATE_CONFERENCE_LINE @"CREATE_CONFERENCELINE"
#define UPDATE_CONFERENCE_LINE @"UPDATE_CONFERENCELINE"
#define DELETE_CONFERENCE_LINE @"DELETE_CONFERENCELINE"
#define CONFERENCE_LINE_CREATED @"CONFERENCELINE_CREATED"
#define CONFERENCE_LINE_UPDATED @"CONFERENCELINE_UPDATED"
#define CONFERENCE_LINE_DELETED @"CONFERENCELINE_DELETED"
#define READ_CONFERENCE_LINES @"READ_CONFERENCELINES"



#define CONFERENCES_MODIFIED @"CONFERENCES_MODIFIED"

#define CREATE_CONFERENCE @"CREATE_CONFERENCE"
#define UPDATE_CONFERENCE @"UPDATE_CONFERENCE"
#define DELETE_CONFERENCE @"DELETE_CONFERENCE"
#define CONFERENCE_CREATED @"CONFERENCE_CREATED"
#define CONFERENCE_UPDATED @"CONFERENCE_UPDATED"
#define CONFERENCE_DELETED @"CONFERENCE_DELETED"
#define READ_CONFERENCES @"READ_CONFERENCES"

#define GROUPS_MODIFIED @"GROUPS_MODIFIED"

#define CREATE_GROUP @"CREATE_GROUP"
#define UPDATE_GROUP @"UPDATE_GROUP"
#define DELETE_GROUP @"DELETE_GROUP"
#define GROUP_CREATED @"GROUP_CREATED"
#define GROUP_UPDATED @"GROUP_UPDATED"
#define GROUP_DELETED @"GROUP_DELETED"
#define READ_GROUPS @"READ_GROUPS"

#define CONFERENCE_TABLE_CELL_ID @"CONFERENCE_TABLE_CELL_ID"
#define CONFERENCE_WAREHOUSE_INIT @"CONFERENCE_WAREHOUSE_INIT"


#endif
